from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..models import (
    AdapterInfo,
    EtherCatState,
    ObjectDictionaryEntry,
    PdoDirection,
    PdoEntry,
    ProcessDataSnapshot,
    SlaveInfo,
)


class BackendError(RuntimeError):
    """Normalized backend error safe to present to the UI."""


class EnvironmentError(BackendError):
    pass


class CommunicationError(BackendError):
    pass


@runtime_checkable
class EtherCatBackend(Protocol):
    @property
    def connected(self) -> bool: ...

    def enumerate_adapters(self) -> list[AdapterInfo]: ...
    def connect(self, adapter_name: str) -> None: ...
    def disconnect(self) -> None: ...
    def scan(self) -> list[SlaveInfo]: ...
    def read_states(self) -> list[SlaveInfo]: ...
    def request_state(
        self, position: int | None, state: EtherCatState, timeout_us: int
    ) -> list[SlaveInfo]: ...
    def reconfig(self, position: int, timeout_us: int) -> bool: ...
    def recover(self, position: int, timeout_us: int) -> bool: ...
    def sdo_read(self, position: int, index: int, subindex: int, size: int = 0) -> bytes: ...
    def sdo_write(self, position: int, index: int, subindex: int, data: bytes) -> None: ...
    def read_object_dictionary(self, position: int) -> list[ObjectDictionaryEntry]: ...
    def read_pdo_mapping(self, position: int, direction: PdoDirection) -> list[PdoEntry]: ...
    def map_process_data(self) -> int: ...
    def exchange_process_data(self, timeout_us: int) -> ProcessDataSnapshot: ...
    def set_output(self, position: int, data: bytes) -> None: ...
    def eeprom_read(self, position: int, word_address: int) -> bytes: ...
    def eeprom_write(self, position: int, word_address: int, data: bytes) -> None: ...
    def register_read(self, position: int, address: int, size: int, timeout_us: int) -> bytes: ...
    def register_write(self, position: int, address: int, data: bytes, timeout_us: int) -> None: ...
